### ISSUE TITLE
error in first file

### ISSUE THREAD

**Issue by Deepak-Perla** [MeidanGR/SpeechEmotionRecognition_Realtime#2]
final_x = nr.reduce_noise(  **_audio_clip=padded_x, 
                          noise_clip=padded_x, 
                          verbose=False_**  )

plt.figure(figsize=(12,2))
librosa.display.waveplot(final_x, sr)
plt.title('Noise-reduced audio')

ipd.display(ipd.Audio(data = final_x, rate=sr))

the highlighted part is not working, what may be the reason

**Comment by MeidanGR** [comment]
> final_x = nr.reduce_noise( **_audio_clip=padded_x, noise_clip=padded_x, verbose=False_** )
> 
> plt.figure(figsize=(12,2)) librosa.display.waveplot(final_x, sr) plt.title('Noise-reduced audio')
> 
> ipd.display(ipd.Audio(data = final_x, rate=sr))
> 
> the highlighted part is not working, what may be the reason

Which error comes up?
I can't see why it isn't working unless 'padded_x' isn't defined.

**Comment by Deepak-Perla** [comment]
![image](https://user-images.githubusercontent.com/71626642/139532007-70bc396b-7cb3-4f27-acaa-df7b21b44d5f.png)
what to do? @MeidanGR

**Comment by MeidanGR** [comment]
> ![image](https://user-images.githubusercontent.com/71626642/139532007-70bc396b-7cb3-4f27-acaa-df7b21b44d5f.png) what to do? @MeidanGR

The reduce_noise function had been updated as part of the update to the noise_reduce library. You can find more information in the docs: https://pypi.org/project/noisereduce/#data

**Comment by ejmfrancisco** [comment]
Hi! I am working with the second file. I received **204288** as the maximum sample length.

![image](https://user-images.githubusercontent.com/85476594/150754551-4c483398-2cd2-4770-97e1-33579c1a66b6.png)

However, during the preprocessing, I always received an error indicating **ValueError: index can't contain negative values**. In that case, I tried to add 1 to the value **204288**. May I know how to solve this issue?

![image](https://user-images.githubusercontent.com/85476594/150754842-c80fb62e-15d7-4720-84e2-1e4d688eb19c.png)
